### ISSUE TITLE
How to get working 2.0.0 agent?

### ISSUE THREAD

**Issue by Irmius** [SkyAPM/SkyAPM-nodejs#119]
In npm libs unable to find 2.0.0 agent
If we add master branch we get the error that ../Network/Common_pb is missing.
Tried to add this lib from agent 1.2.0, but it doesn't work and we get other files are missing.

Would like to know how to make 2.0.0 agent work.
1.2.0 agent works fine.

```
`npm run check && npm run generate-source

> skyapm-nodejs@2.0.0 check /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
> eslint lib/ && eslint index.js


> skyapm-nodejs@2.0.0 generate-source /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
> run-script-os


> skyapm-nodejs@2.0.0 generate-source:darwin:linux /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
> rm -rf lib/network && mkdir -p lib/network && cd proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto

common/*.proto: No such file or directory
/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^

Error: Command failed: /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/grpc-tools/bin/grpc_node_plugin --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto
common/*.proto: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/grpc-tools/bin/grpc_node_plugin --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skyapm-nodejs@2.0.0 generate-source:darwin:linux: `rm -rf lib/network && mkdir -p lib/network && cd proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skyapm-nodejs@2.0.0 generate-source:darwin:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/irmantas/.npm/_logs/2020-06-18T07_13_29_388Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skyapm-nodejs@2.0.0 generate-source: `run-script-os`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skyapm-nodejs@2.0.0 generate-source script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/irmantas/.npm/_logs/2020-06-18T07_13_29_404Z-debug.log
`
```

```
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'generate-source' ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [ 'pregenerate-source', 'generate-source', 'postgenerate-source' ]
5 info lifecycle skyapm-nodejs@2.0.0~pregenerate-source: skyapm-nodejs@2.0.0
6 info lifecycle skyapm-nodejs@2.0.0~generate-source: skyapm-nodejs@2.0.0
7 verbose lifecycle skyapm-nodejs@2.0.0~generate-source: unsafe-perm in lifecycle true
8 verbose lifecycle skyapm-nodejs@2.0.0~generate-source: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/.bin:/home/irmantas/projects/instat/in-instat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle skyapm-nodejs@2.0.0~generate-source: CWD: /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
10 silly lifecycle skyapm-nodejs@2.0.0~generate-source: Args: [ '-c', 'run-script-os' ]
11 silly lifecycle skyapm-nodejs@2.0.0~generate-source: Returned: code: 1  signal: null
12 info lifecycle skyapm-nodejs@2.0.0~generate-source: Failed to exec generate-source script
13 verbose stack Error: skyapm-nodejs@2.0.0 generate-source: `run-script-os`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid skyapm-nodejs@2.0.0
15 verbose cwd /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
16 verbose Linux 5.3.0-59-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "generate-source"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error skyapm-nodejs@2.0.0 generate-source: `run-script-os`
22 error Exit status 1
23 error Failed at the skyapm-nodejs@2.0.0 generate-source script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
```

**Comment by Irmius** [comment]
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'generate-source:darwin:linux'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [
4 verbose run-script   'pregenerate-source:darwin:linux',
4 verbose run-script   'generate-source:darwin:linux',
4 verbose run-script   'postgenerate-source:darwin:linux'
4 verbose run-script ]
5 info lifecycle skyapm-nodejs@2.0.0~pregenerate-source:darwin:linux: skyapm-nodejs@2.0.0
6 info lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: skyapm-nodejs@2.0.0
7 verbose lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: unsafe-perm in lifecycle true
8 verbose lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent/node_modules/.bin:/home/irmantas/projects/instat/in-instat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: CWD: /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
10 silly lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'rm -rf lib/network && mkdir -p lib/network && cd proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto'
10 silly lifecycle ]
11 silly lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: Returned: code: 1  signal: null
12 info lifecycle skyapm-nodejs@2.0.0~generate-source:darwin:linux: Failed to exec generate-source:darwin:linux script
13 verbose stack Error: skyapm-nodejs@2.0.0 generate-source:darwin:linux: `rm -rf lib/network && mkdir -p lib/network && cd proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid skyapm-nodejs@2.0.0
15 verbose cwd /home/irmantas/projects/instat/in-instat/node_modules/skyapm-nodejs/modules/nodejs-agent
16 verbose Linux 5.3.0-59-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "generate-source:darwin:linux"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error skyapm-nodejs@2.0.0 generate-source:darwin:linux: `rm -rf lib/network && mkdir -p lib/network && cd proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../lib/network/ --grpc_out=../lib/network/ common/*.proto language-agent/Tracing.proto management/*.proto`
22 error Exit status 1
23 error Failed at the skyapm-nodejs@2.0.0 generate-source:darwin:linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kezhenxu94** [comment]
`common/*.proto: No such file or directory`


please also check out the submodules first, FYI `git submodule update --init`, or Googling how
