### ISSUE TITLE
Exception information: “Error: 14 UNAVAILABLE: Trying to connect an http1.x server”

### ISSUE THREAD

**Issue by djb19841006** [SkyAPM/SkyAPM-nodejs#41]
1.  skywalking version：5.0.0-RC2

2. nodejs code：
require('skywalking-nodejs').start({
    applicationCode: 'test',
    directServers: '172.17.35.204:11800'
});

3. error message ：
Error: 14 UNAVAILABLE: Trying to connect an http1.x server
    at Object.exports.createStatusError (E:\source\webservice\nodeTest\node_modules\grpc\src\common.js:87:15)
    at Object.onReceiveStatus (E:\source\webservice\nodeTest\node_modules\grpc\src\client_interceptors.js:1188:28)
    at InterceptingListener._callNext (E:\source\webservice\nodeTest\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (E:\source\webservice\nodeTest\node_modules\grpc\src\client_interceptors.js:614:8)
    at callback (E:\source\webservice\nodeTest\node_modules\grpc\src\client_interceptors.js:841:24)

**Comment by ascrutae** [comment]
I cannot reproduce this issue in local machine. Could you send me an demo or use the latest version?
