### ISSUE TITLE
node v4.8.4 can't use this agent?

### ISSUE THREAD

**Issue by guoyunlong666** [SkyAPM/SkyAPM-nodejs#61]
my app can't startup,this is error:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/www/nodejs/node_modules/skyapm-nodejs/lib/instrumentation/index.js:22:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ascrutae** [comment]
It seem like the agent miss ‘strict’, I will try to fix it.

**Comment by guoyunlong666** [comment]
That's great. Thank you.

**Comment by ascrutae** [comment]
@guoyunlong666  This issue had fixed, and I'm afraid not that current version cannot running in node.js 4.8.4, because of the GRPC that node.js agent use it to send data to the collector cannot running in node.js 4.8.4.

**Comment by ascrutae** [comment]
Ref: #62

**Comment by ascrutae** [comment]
Close this issue.
