### ISSUE TITLE
6.0.0-GA cross app examples tracing error

### ISSUE THREAD

**Issue by liudingnet** [SkyAPM/SkyAPM-nodejs#77]
6.0.0-GA, standalone, skyapm-nodejs1.1.0 cross app example,serverA & serverB could run correctly, when serverA calls serverB, throw exception, seeing the screenshot

**serverB exception:**
C:\Users\lenovo\WebstormProjects\untitled1\node_modules\mysql\lib\protocol\Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:101:603)
    at Object.goog.asserts.doAssertFailure_ (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:102:126)
    at Object.goog.asserts.assert (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:102:385)
    at jspb.BinaryWriter.writeInt32 (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:330:264)
    at proto.SegmentReference.serializeBinaryToWriter (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\skyapm-nodejs\lib\network\language-agent-v2\trace_pb.js:558:12)
    at jspb.BinaryWriter.writeRepeatedMessage (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:350:385)
    at proto.SpanObjectV2.serializeBinaryToWriter (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\skyapm-nodejs\lib\network\language-agent-v2\trace_pb.js:981:12)
    at jspb.BinaryWriter.writeRepeatedMessage (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\google-protobuf\google-protobuf.js:350:385)
    at Function.proto.SegmentObject.serializeBinaryToWriter (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\skyapm-nodejs\lib\network\language-agent-v2\trace_pb.js:179:12)
    at proto.SegmentObject.serializeBinary (C:\Users\lenovo\WebstormProjects\untitled1\node_modules\skyapm-nodejs\lib\network\language-agent-v2\trace_pb.js:155:23)

**backend Server exception:**
Apr 01, 2019 9:46:39 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@120c52eb
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onError(TraceSegmentReportServiceHandler.java:66)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by CrazyPandar** [comment]
this problem also exists within 1.1.2 release
