### ISSUE TITLE
unCaught exception: TypeError: RegisterParameteres.Enpoints is not a constructor

### ISSUE THREAD

**Issue by ajoysahu** [SkyAPM/SkyAPM-nodejs#95]
Observed the below error with latest version:

error: unCaught exception: TypeError: RegisterParameteres.Enpoints is not a constructor
    at RemoteClient.registerEndpoint (/lib/services/remote-client-service.js:121:32)
    at Timeout._onTimeout (/lib/dictionary/endpoint-dictionary.js:51:54)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) uid=19151820-3db1-11ea-b80b-a7e8dd8929f2

Look like there is a typo @ line https://github.com/SkyAPM/SkyAPM-nodejs/blob/5bf02d352df4b38115d6029d6b5b1811a6d1ca00/modules/nodejs-agent/lib/services/remote-client-service.js#L121

Should be new RegisterParameteres.Endpoints();

**Comment by kezhenxu94** [comment]
Fixed by #102
